name: Build
on:
  #schedule:
  #  - cron: "30 2 1 * *"
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:
    types: [build]

concurrency: 
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build WSA
    runs-on: windows-2019
    

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet packages
        run: nuget restore WebNovelConverter.sln

  
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

#- name: Restore Packages
#  run: nuget restore MySolution.sln

      - name: Build solution
        run: msbuild WebNovelConverter.sln -t:rebuild -property:Configuration=Release
